modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="hhamsters"
version="${1.0}"
displayName="Hamtastic Hamsters!"
logoFile="hhamsters_logo.png"
authors="DragN0007"
description='''
Adds Hamsters and decor!
'''
[[dependencies.hhamsters]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hhamsters]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.hhamsters]]
modId="geckolib"
mandatory=true
versionRange = "[4.4.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.hhamsters]]
modId="dragnlivestock"
mandatory=true
versionRange = "[2.5,)"
ordering="NONE"
side="BOTH"